<?php

namespace AppBundle\Repository;

/**
 * TESTRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TESTRepository extends \Doctrine\ORM\EntityRepository
{
}
