easy_admin:
    entities:
        # change the following to the namespaces of your own entities
        - AppBundle\Entity\Product
        - AppBundle\Entity\Invoice
        - AppBundle\Entity\Customer
        - AppBundle\Entity\BTW
        - AppBundle\Entity\StaffGroup
        - AppBundle\Entity\StaffDiscount